### ISSUE TITLE
SolidPython2 JupyterSCAD integration

### ISSUE THREAD

**Issue by jeff-dh** [jreiberkyle/jupyterscad#17]
What do you think about this:

This change to SolidPython2:
```diff
diff --git a/solid2/core/object_base/object_base_impl.py b/solid2/core/object_base/object_base_impl.py
index 060d671..b845a45 100644
--- a/solid2/core/object_base/object_base_impl.py
+++ b/solid2/core/object_base/object_base_impl.py
@@ -20,6 +20,11 @@ class RenderMixin:
         from ..scad_render import render_to_stl_file
         return render_to_stl_file(self, filename)
 
+    def _ipython_display_(self):
+        from jupyterscad import render
+        from IPython.display import display
+        display(render(self))
+
 class ObjectBase(RenderMixin):
     def __init__(self):
         self._children = []

```

makes this possible:

![Screenshot_2023-10-17_23-34-25](https://github.com/jreiberkyle/jupyterscad/assets/1105041/f3ce21f4-60bd-489f-857c-46f58e8702c1)

**Comment by jreiberkyle** [comment]
that's sweet! So this is a change from outputting the openscad code to displaying the render? For my workflow, it's ideal. If I need the openscad code, I can use `str(obj)` to still get it, right?

**Comment by jreiberkyle** [comment]
May want to add in a check for jupyterscad being installed if you don't want to make it a dependency.

**Comment by jeff-dh** [comment]
Yeah, checking whether it's installed or not is a good idea, let me think about it.....


You can get the scad code with `str(cube())` but I would suggest `cube().as_scad()`:

![solidjupyter](https://github.com/jreiberkyle/jupyterscad/assets/1105041/5d9e8971-0433-41f4-af51-b8b3dadfa714)

**Comment by jeff-dh** [comment]
The latest master-2.0.0..... head contains this, check it out

**Comment by jreiberkyle** [comment]
Works great! 

![image](https://github.com/jreiberkyle/jupyterscad/assets/2984664/fe814c68-990e-4318-99a1-0c0694101f3e)
