### ISSUE TITLE
change `render` to `view` to avoid namespace clash with OpenSCAD

### ISSUE THREAD

**Issue by jreiberkyle** [jreiberkyle/jupyterscad#24]
OpenSCAD already has a `render` function, and using `from solid2 import *` can cause that `render` to override `jupyterscad.render`. To avoid this clash, change `jupyterscad.render` to `jupyterscad.view`.

**Comment by jreiberkyle** [comment]
@jeff-dh this actually seems like the most graceful solution to https://github.com/jeff-dh/SolidPython/issues/48 - no conflicts.

**Comment by jeff-dh** [comment]
:+1:
