### ISSUE TITLE
Color Support

### ISSUE THREAD

**Issue by kylekyle** [jreiberkyle/jupyterscad#5]
[STL doesn't support color](https://github.com/openscad/openscad/issues/4671), which is why the `color` commands do nothing in JupyterSCAD. There are really two paths to supporting color: 

1. Export to a format that supports color, such as 3MF or DXF. `jupyterlab-viewer-3d` could render, but [it doesn't support the latest version of JupyterLab](https://github.com/pschatzmann/jupyterlab-viewer-3d/issues/21). This would require very few changes to JupyterSCAD. 

2. [Export each color separately](https://erik.nygren.org/2018-3dprint-multicolor-openscad.html), then used something like [K3D](https://k3d-jupyter.org/) to import each color into a single plot for rendering in Jupyter. This would be a heavier lift.

**Comment by jreiberkyle** [comment]
Thank you for this breakdown! great info here. Are you requesting color support here? The color commands in JupyterSCAD are just used in visualization, not for rendering an stl. And yes, the visualization is just all one color. Like openscad but without support for holes/transparency for debugging.

**Comment by kylekyle** [comment]
Yes, I am requesting color support. I would like to be able to render various objects in various colors in jupyterscad in the same way that you can in OpenSCAD.

**Comment by jreiberkyle** [comment]
got it. the renderer used, pythreejs, also supports colors so this could be supported. The objects would need to be distinct, not all rolled up into one object, but that should be a reasonable compromise.

[openscad color support](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Changing_the_colour_of_an_object), for ref

**Comment by jreiberkyle** [comment]
Determined to be out of scope, use OpenSCAD viewer (external editor) for this capability.
