### ISSUE TITLE
grid (almost) becomes plane with bigger objects

### ISSUE THREAD

**Issue by jeff-dh** [jreiberkyle/jupyterscad#9]
The grid size for the x-, y-, and z-plane seem to be constant (probably 1?) and if a bigger object is rendered with jupyterscad the grids (almost) look like planes.

![grid_almost_becomes_plane](https://github.com/jreiberkyle/jupyterscad/assets/1105041/f672818e-edba-448f-bdde-1d736aa59c17)

(if you zoom out a little more the grids really look like planes)

I think the cell size of the grid should somehow scale with the model or at least be increased.

The image renders [this example](https://github.com/jeff-dh/SolidPython/blob/master-2.0.0-beta-dev/solid2/examples/06-functions.py) from the solid2 repo.

**Comment by jeff-dh** [comment]
Found `grid_unit`..... but wondering whether some automatic "detection" of a good grid unit would be cool?

Something based on `mesh.min_` and `mesh.max_`?

**Comment by jreiberkyle** [comment]
For the future, absolutely automatic detection would be great. For now, I can elevate awareness of the `grid_unit` parameter to where `render` and `visualize_stl` are introduced.

**Comment by jreiberkyle** [comment]
closed by #16
